--- 
eureka: 
  client: 
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl: 
      defaultZone: "http://localhost:8761/eureka"
  instance: 
    hostname: localhost
hystrix: 
  command: 
    default: 
      execution: 
        isolation: 
          thread: 
            timeoutInMilliseconds: 40000000
logging: 
  file: checkout.log
  level: INFO
  path: "C:/sameer/spring_cloud_git"
ribbon: 
  ConnectTimeout: 30000
  ReadTimeout: 60000
server: 
  port: 8082
spring: 
  application: 
    name: checkout